version: '3.1'

services:

  start:
    image: php:7.2-apache
    restart: always
    container_name: start
    volumes:
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=start.abendstille.at
    networks:
      - revproxy

networks:
  revproxy:
    external: true
